-- Generated by drizzle-kit, then made re-runnable (IF NOT EXISTS / duplicate_object
-- guards) so applying it to an already-migrated database is a no-op.
DO $$ BEGIN
	CREATE TYPE "public"."offer_monetization" AS ENUM('flatrate', 'free', 'ads', 'rent', 'buy');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	CREATE TYPE "public"."title_kind" AS ENUM('movie', 'series');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "genres" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "genres_name_not_blank" CHECK (btrim("genres"."name") <> '')
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "keywords" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "keywords_name_not_blank" CHECK (btrim("keywords"."name") <> '')
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "movies" (
	"title_id" bigint PRIMARY KEY NOT NULL,
	"kind" "title_kind" DEFAULT 'movie' NOT NULL,
	"runtime_minutes" smallint,
	"imdb_id" text,
	CONSTRAINT "movies_kind_is_movie" CHECK ("movies"."kind" = 'movie'),
	CONSTRAINT "movies_runtime_positive" CHECK ("movies"."runtime_minutes" > 0),
	CONSTRAINT "movies_imdb_id_format" CHECK ("movies"."imdb_id" ~ '^tt[0-9]+$')
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seasons" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "seasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"series_id" bigint NOT NULL,
	"season_number" smallint NOT NULL,
	"name" text,
	"overview" text,
	"air_date" date,
	"episode_count" smallint,
	"poster_path" text,
	CONSTRAINT "seasons_series_id_season_number_key" UNIQUE("series_id","season_number"),
	CONSTRAINT "seasons_season_number_nonnegative" CHECK ("seasons"."season_number" >= 0),
	CONSTRAINT "seasons_episode_count_nonnegative" CHECK ("seasons"."episode_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "series" (
	"title_id" bigint PRIMARY KEY NOT NULL,
	"kind" "title_kind" DEFAULT 'series' NOT NULL,
	"status" text,
	"last_air_date" date,
	"episode_runtime_minutes" smallint,
	"season_count" smallint,
	CONSTRAINT "series_kind_is_series" CHECK ("series"."kind" = 'series'),
	CONSTRAINT "series_episode_runtime_positive" CHECK ("series"."episode_runtime_minutes" > 0),
	CONSTRAINT "series_season_count_nonnegative" CHECK ("series"."season_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "title_availability" (
	"title_id" bigint NOT NULL,
	"region" text DEFAULT 'US' NOT NULL,
	"source" text DEFAULT 'tmdb-justwatch' NOT NULL,
	"link" text,
	"fetched_at" timestamp with time zone NOT NULL,
	CONSTRAINT "title_availability_pkey" PRIMARY KEY("title_id","region"),
	CONSTRAINT "title_availability_region_us" CHECK ("title_availability"."region" = 'US')
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "title_embeddings" (
	"title_id" bigint NOT NULL,
	"model" text NOT NULL,
	"dimensions" smallint NOT NULL,
	"embedding" vector NOT NULL,
	"content_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "title_embeddings_pkey" PRIMARY KEY("title_id","model"),
	CONSTRAINT "title_embeddings_model_not_blank" CHECK (btrim("title_embeddings"."model") <> ''),
	CONSTRAINT "title_embeddings_dimensions_match" CHECK ("title_embeddings"."dimensions" > 0 and vector_dims("title_embeddings"."embedding") = "title_embeddings"."dimensions")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "title_genres" (
	"title_id" bigint NOT NULL,
	"genre_id" integer NOT NULL,
	CONSTRAINT "title_genres_pkey" PRIMARY KEY("title_id","genre_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "title_keywords" (
	"title_id" bigint NOT NULL,
	"keyword_id" integer NOT NULL,
	CONSTRAINT "title_keywords_pkey" PRIMARY KEY("title_id","keyword_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "title_offers" (
	"title_id" bigint NOT NULL,
	"region" text DEFAULT 'US' NOT NULL,
	"provider_id" integer NOT NULL,
	"monetization" "offer_monetization" NOT NULL,
	CONSTRAINT "title_offers_pkey" PRIMARY KEY("title_id","region","provider_id","monetization")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "titles" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "titles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kind" "title_kind" NOT NULL,
	"tmdb_id" integer NOT NULL,
	"title" text NOT NULL,
	"original_title" text,
	"original_language" text,
	"overview" text,
	"release_date" date,
	"poster_path" text,
	"popularity" real,
	"vote_average" real,
	"vote_count" integer,
	"tmdb_fetched_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "titles_kind_tmdb_id_key" UNIQUE("kind","tmdb_id"),
	CONSTRAINT "titles_id_kind_key" UNIQUE("id","kind"),
	CONSTRAINT "titles_tmdb_id_positive" CHECK ("titles"."tmdb_id" > 0),
	CONSTRAINT "titles_title_not_blank" CHECK (btrim("titles"."title") <> ''),
	CONSTRAINT "titles_popularity_nonnegative" CHECK ("titles"."popularity" >= 0),
	CONSTRAINT "titles_vote_average_range" CHECK ("titles"."vote_average" between 0 and 10),
	CONSTRAINT "titles_vote_count_nonnegative" CHECK ("titles"."vote_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "watch_providers" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"logo_path" text,
	CONSTRAINT "watch_providers_name_not_blank" CHECK (btrim("watch_providers"."name") <> '')
);
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "movies" ADD CONSTRAINT "movies_title_fkey" FOREIGN KEY ("title_id","kind") REFERENCES "public"."titles"("id","kind") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "seasons" ADD CONSTRAINT "seasons_series_id_series_title_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."series"("title_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "series" ADD CONSTRAINT "series_title_fkey" FOREIGN KEY ("title_id","kind") REFERENCES "public"."titles"("id","kind") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_availability" ADD CONSTRAINT "title_availability_title_id_titles_id_fk" FOREIGN KEY ("title_id") REFERENCES "public"."titles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_embeddings" ADD CONSTRAINT "title_embeddings_title_id_titles_id_fk" FOREIGN KEY ("title_id") REFERENCES "public"."titles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_genres" ADD CONSTRAINT "title_genres_title_id_titles_id_fk" FOREIGN KEY ("title_id") REFERENCES "public"."titles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_genres" ADD CONSTRAINT "title_genres_genre_id_genres_id_fk" FOREIGN KEY ("genre_id") REFERENCES "public"."genres"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_keywords" ADD CONSTRAINT "title_keywords_title_id_titles_id_fk" FOREIGN KEY ("title_id") REFERENCES "public"."titles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_keywords" ADD CONSTRAINT "title_keywords_keyword_id_keywords_id_fk" FOREIGN KEY ("keyword_id") REFERENCES "public"."keywords"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_offers" ADD CONSTRAINT "title_offers_provider_id_watch_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."watch_providers"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_offers" ADD CONSTRAINT "title_offers_availability_fkey" FOREIGN KEY ("title_id","region") REFERENCES "public"."title_availability"("title_id","region") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_availability_fetched_at_idx" ON "title_availability" USING btree ("fetched_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_genres_genre_id_idx" ON "title_genres" USING btree ("genre_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_keywords_keyword_id_idx" ON "title_keywords" USING btree ("keyword_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_offers_provider_monetization_idx" ON "title_offers" USING btree ("provider_id","monetization","title_id");
