-- Generated by drizzle-kit, then made re-runnable (IF NOT EXISTS / duplicate_object
-- guards) so applying it to an already-migrated database is a no-op.
DO $$ BEGIN
	CREATE TYPE "public"."lifecycle_status" AS ENUM('active', 'unavailable', 'tombstoned');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
	CREATE TYPE "public"."tombstone_reason" AS ENUM('source_deleted', 'source_id_collision');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "title_lifecycle" (
	"title_id" bigint PRIMARY KEY NOT NULL,
	"status" "lifecycle_status" NOT NULL,
	"first_seen_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone NOT NULL,
	"last_successful_refresh_at" timestamp with time zone,
	"last_observed_at" timestamp with time zone NOT NULL,
	"last_observation_run_id" text NOT NULL,
	"missing_since" timestamp with time zone,
	"consecutive_missing" smallint DEFAULT 0 NOT NULL,
	"tombstoned_at" timestamp with time zone,
	"tombstone_reason" "tombstone_reason",
	"restored_at" timestamp with time zone,
	"restore_count" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "title_lifecycle_counts_nonnegative" CHECK ("title_lifecycle"."consecutive_missing" >= 0 and "title_lifecycle"."restore_count" >= 0),
	CONSTRAINT "title_lifecycle_run_id_not_blank" CHECK (btrim("title_lifecycle"."last_observation_run_id") <> ''),
	CONSTRAINT "title_lifecycle_tombstone_consistent" CHECK (("title_lifecycle"."status" = 'tombstoned') = ("title_lifecycle"."tombstoned_at" is not null and "title_lifecycle"."tombstone_reason" is not null)),
	CONSTRAINT "title_lifecycle_active_not_missing" CHECK ("title_lifecycle"."status" <> 'active' or ("title_lifecycle"."missing_since" is null and "title_lifecycle"."consecutive_missing" = 0))
);
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "title_lifecycle" ADD CONSTRAINT "title_lifecycle_title_id_titles_id_fk" FOREIGN KEY ("title_id") REFERENCES "public"."titles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_lifecycle_tombstoned_idx" ON "title_lifecycle" USING btree ("tombstoned_at") WHERE "title_lifecycle"."status" = 'tombstoned';
